"I Think a computer program is an program that gives certain intructions for an computer to understand"
"My favorite food would be tacos"
"I buy ground beef or ground turkey from the grocery store"
"I wash the ground beef or ground turkey "
"I put vegetable oil in a skillet put the cooking meat inside the skillet"
"I let the meat cook until no pink is visible in the meat"
"I then drain any leftover liquid or water from the meat and skillet"
"I then season the meat with taco seasoning,cheese, and any vegetable available"
"Toast the taco shells until my liking them proceed to eat"